version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: dev-helper-server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/devhelper
    volumes:
      - ./server:/app

  client:
    build: ./client
    container_name: dev-helper-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app

volumes:
  mongo-data:
